blog/urls.py
from django.urls import path
from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
    like,
)

app_name = 'blog'
urlpatterns = [
    path('', post_list, name='list'),
    path('create/', post_create, name='create'),
    
    # path('detail/<str:slug>/', post_detail, name='detail'),
    path('<str:slug>/', post_detail, name='detail'),
    
    # path('update/<str:slug>/', post_update, name='update'),
    path('<str:slug>/update/', post_update, name='update'),

    # path('delete/<str:slug>/', post_delete, name='delete'),
    path('<str:slug>/delete/', post_delete, name='delete'),

    path('<str:slug>/like/', like, name='like'),
] 

main/urls.py
from django.contrib import admin
from django.urls import path, include
# for statics and medias
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]

# for statics and medias
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'blog/main.css' %}">


    <title>Umit Blog</title>
</head>
<body>
    {% include 'navbar.html' %}
    <!-- for messages -->
    <div class="container message">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
          {{ message }}
        </div>  
        {% endfor %}
        {% endif %}
    </div>

    <div class="container">
    {% block content %}
        
    {% endblock content %}
    </div>

    <!-- Bootstrap Script -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
    <!-- Fontawesome Script -->
    <script src="https://kit.fontawesome.com/f3876d5d9f.js" crossorigin="anonymous"></script>
    
    <!-- timeout.js Script -->
    <script src="{% static 'blog/timeout.js' %}"></script>

</body>
</html>

templates/navbar.html
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top ">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog:list' %}">Umit Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar Toggle" 
            aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toogler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog:list' %}">Home</a>
                    <a class="nav-item nav-link" href="#">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}

                        {% comment %} {% url 'logout' %} {% endcomment %}                      
                        <form action="{% url 'logout' %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="nav-item nav-link btn btn-link logout-btn">Logout</button>
                        </form>

                        {% comment %} {% url 'profile' %} {% endcomment %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'blog:create' %}">New Post</a>
                    {% else %}
                        {% comment %} {% url 'login' %} {% endcomment %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        {% comment %} {% url 'register' %} {% endcomment %}
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>